modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="survivalmod"
version="0.0.,1-1.19"
displayName="Def Daemon's Survival Mod"
logoFile="survivalmod.png"
credits="Special thnx to all the guys who are creating tutorials about modding and making modding for me possible..."
authors="Def Daemon"
description='''
A brand new survival mod for Minecraft 1.19...
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.survivalmod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[43,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.survivalmod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
